karyotype = data/karyotype.txt
chromosomes_units = 1

<image>
dir = .
file = circos.png
png = yes
svg = no
radius = 1500p
background = white
</image>

<ideogram>

<spacing>
default = 5u
break   = 5u
</spacing>

radius           = 1.8r
thickness        = 45p
fill             = yes
stroke_thickness = 3p
stroke_color     = white
show_label       = yes
label_radius     = 2.4r
label_size       = 18p
label_font       = condensed
label_color      = black

<rules>
<rule>
condition = /^maj_arts$/
fill_color = #5B7FA6
</rule>
<rule>
condition = /^maj_comm$/
fill_color = #4A6FA5
</rule>
<rule>
condition = /^maj_social$/
fill_color = #C8915F
</rule>
<rule>
condition = /^maj_business$/
fill_color = #C17E47
</rule>
<rule>
condition = /^maj_education$/
fill_color = #C99070
</rule>
<rule>
condition = /^maj_engineering$/
fill_color = #558B2F
</rule>
<rule>
condition = /^maj_natural$/
fill_color = #7CB342
</rule>
<rule>
condition = /^job/
fill_color = #8B8B8B
</rule>
</rules>

</ideogram>

<links>
<link>
file          = data/links.txt
radius        = 1.7r
ribbon        = yes
bezier_radius = 0.3r
thickness     = 2p
stroke        = no

<rules>
condition = 1
show      = yes
</rules>
</link>
</links>

<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>
